
const CONTRACT_ADDRESS = "0xa0865422e964feb6bf885ac8bf3420a70ef8b61c9e56b4e18ccdd666a25e62ff";
const apiKey = '8baef3850b99477bb204280ff5a3c7b0';
const NODE_URL = `https://api.nodesmith.io/v1/aion/testnet/jsonrpc?apiKey=${apiKey}`;

const BOND_ABI = [ { outputs: [ [Object] ],
  constant: false,
  payable: false,
  inputs: [ [Object], [Object] ],
  name: 'isFriend',
  type: 'function' },
{ outputs: [ [Object], [Object], [Object], [Object], [Object] ],
  constant: false,
  payable: false,
  inputs: [ [Object] ],
  name: 'getResolution',
  type: 'function' },
{ outputs: [ [Object] ],
  constant: true,
  payable: false,
  inputs: [],
  name: 'resolutionCount',
  type: 'function' },
{ outputs: [ [Object] ],
  constant: false,
  payable: false,
  inputs: [ [Object] ],
  name: 'finalResult',
  type: 'function' },
{ outputs: [ [Object], [Object], [Object] ],
  constant: false,
  payable: false,
  inputs: [ [Object], [Object] ],
  name: 'getFriend',
  type: 'function' },
{ outputs: [],
  constant: false,
  payable: true,
  inputs:
   [ [Object],
     [Object],
     [Object],
     [Object],
     [Object],
     [Object],
     [Object],
     [Object] ],
  name: 'newResolution',
  type: 'function' },
{ outputs: [],
  constant: false,
  payable: false,
  inputs: [ [Object], [Object] ],
  name: 'makeVote',
  type: 'function' },
{ outputs: [],
  inputs: [ [Object] ],
  name: 'ResolutionCreated',
  anonymous: false,
  type: 'event' },
{ outputs: [],
  inputs: [ [Object], [Object] ],
  name: 'VoteCreated',
  anonymous: false,
  type: 'event' },
{ outputs: [],
  inputs: [ [Object] ],
  name: 'ResolutionCompleted',
  anonymous: false,
  type: 'event' } ];

module.exports = {
  CONTRACT_ADDRESS,
  NODE_URL,
  BOND_ABI,
}